=== api-evangelist/amazon-iot-events/json-schema/iot-events-alarm-model-version-summaries-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-iot-events/refs/heads/main/json-schema/iot-events-alarm-model-version-summaries-schema.json",
  "title": "AlarmModelVersionSummaries",
  "description": "AlarmModelVersionSummaries schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "alarmModelName": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AlarmModelName"
          },
          {
            "description": "The name of the alarm model."
          }
        ]
      },
      "alarmModelArn": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AlarmModelArn"
          },
          {
            "description": "The ARN of the alarm model. For more information, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\">Amazon Resource Names (ARNs)</a> in the <i>AWS General Reference</i>."
          }
        ]
      },
      "alarmModelVersion": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AlarmModelVersion"
          },
          {
            "description": "The version of the alarm model."
          }
        ]
      },
      "roleArn": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AmazonResourceName"
          },
          {
            "description": "The ARN of the IAM role that allows the alarm to perform actions and access AWS resources. For more information, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\">Amazon Resource Names (ARNs)</a> in the <i>AWS General Reference</i>."
          }
        ]
      },
      "creationTime": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Timestamp"
          },
          {
            "description": "The time the alarm model was created, in the Unix epoch format."
          }
        ]
      },
      "lastUpdateTime": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Timestamp"
          },
          {
            "description": "The time the alarm model was last updated, in the Unix epoch format."
          }
        ]
      },
      "status": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AlarmModelVersionStatus"
          },
          {
            "description": "<p>The status of the alarm model. The status can be one of the following values:</p> <ul> <li> <p> <code>ACTIVE</code> - The alarm model is active and it's ready to evaluate data.</p> </li> <li> <p> <code>ACTIVATING</code> - AWS IoT Events is activating your alarm model. Activating an alarm model can take up to a few minutes.</p> </li> <li> <p> <code>INACTIVE</code> - The alarm model is inactive, so it isn't ready to evaluate data. Check your alarm model information and update the alarm model.</p> </li> <li> <p> <code>FAILED</code> - You couldn't create or update the alarm model. Check your alarm model information and try again.</p> </li> </ul>"
          }
        ]
      },
      "statusMessage": {
        "allOf": [
          {
            "$ref": "#/components/schemas/StatusMessage"
          },
          {
            "description": " Contains information about the status of the alarm model version. "
          }
        ]
      }
    },
    "description": "Contains a summary of an alarm model version."
  }
}

=== api-evangelist/amazon-iot-events/examples/iot-events-alarm-model-version-summary-example.json
{
  "alarmModelName": "example-resource",
  "alarmModelArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "alarmModelVersion": "example-value",
  "roleArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "creationTime": "2025-03-15T14:30:00Z",
  "lastUpdateTime": "2025-03-15T14:30:00Z",
  "status": "ACTIVE",
  "statusMessage": "ACTIVE"
}
